package br.ufes.dwws.ufespay.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.EntityNotFoundException;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import br.ufes.dwws.ufespay.core.domain.Comment;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CommentDAOJPA extends BaseJPADAO<Comment> implements CommentDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Comment getById(Long id) {
		return this.retrieveById(id);
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void delete(Long id) {
		Comment comment = this.retrieveById(id);
		
		if (comment == null)
			throw new EntityNotFoundException("Could not find comment ID: + " + id+"\n");
		else {
			entityManager.remove(comment);
		}
	}

}