package br.ufes.dwws.ufespay.core.persistence;

import java.util.Collection;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface TransactionDAO extends BaseDAO<Transaction> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Transaction getById(Long id);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Transaction update(Transaction transac);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection<Transaction> getAll();

}