package br.ufes.dwws.ufespay.core.persistence;

import java.util.Collection;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import br.ufes.dwws.ufespay.core.domain.User;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UserDAOJPA extends BaseJPADAO<User> implements UserDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public User getByEmail(String email) {
		String query = "select u from loggeduser u where u.email = :email";
		return ((entityManager.createQuery(query, User.class)).setParameter("email", email)).getSingleResult();
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection<User> getAll() {
		return this.retrieveAll();
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public User getById(Long id) {
		
		return this.retrieveById(id);
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public User update(User user) {
		User userUpdated= null;
	
		//entityManager.getTransaction().begin();
		userUpdated = entityManager.merge(user);
		//entityManager.getTransaction().commit();
		return userUpdated;
	}

}