package br.ufes.dwws.ufespay.core.persistence;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.User;
import br.ufes.dwws.ufespay.core.domain.Wallet;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface WalletDAO extends BaseDAO<Wallet> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Wallet getById(Long id);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Wallet update(Wallet wallet);

}