package br.ufes.dwws.ufespay.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;

import br.ufes.dwws.ufespay.core.domain.Wallet;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class WalletDAOJPA extends BaseJPADAO<Wallet> implements WalletDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Wallet getById(Long id) {
		return this.retrieveById(id);
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Wallet update(Wallet wallet) {
		Wallet walletUpdated= null;
		
		//entityManager.getTransaction().begin();
		walletUpdated = entityManager.merge(wallet);
		//entityManager.getTransaction().commit();
		return walletUpdated;
	}

}