package br.ufes.dwws.ufespay.core.domain;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Comment extends PersistentObjectSupport implements Comparable<Comment> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;


	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String text;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	@JoinColumn(name="transactionId", referencedColumnName = "id")
	private Transaction transaction;

	@OneToOne
	@JoinColumn(name = "authorId", referencedColumnName = "id")
	private User author;

	/** Getter for text. */
	public String getText() {
		return text;
	}

	/** Setter for text. */
	public void setText(String text) {
		this.text = text;
	}

	public Transaction getTransaction() {
		return transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	public User getAuthor() {
		return author;
	}

	public void setAuthor(User author) {
		this.author = author;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Comment o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}