package br.ufes.dwws.ufespay.core.domain;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity()
@Table(name = "LoggedUser" )
public class User extends PersistentObjectSupport implements Comparable<User> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 300)
	private String name;


	@NotNull
	@Size(max = 30)
	@Column(unique=true)
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 100)
	private String password;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date created_at;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date updated_at;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(
			fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "walletId")
	private Wallet wallet;

	
    @PrePersist
    public void setCreatedDate() {
    	this.setCreated_at( new Timestamp((new Date()).getTime()));
    }
    
    @PreUpdate
    public void setUpdateDate() {
    	this.setUpdated_at( new Timestamp((new Date()).getTime()));
    }
	

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}



	public String getPassword() {
		return password;
	}



	public void setPassword(String password) {
		this.password = password;
	}



	public Date getCreated_at() {
		return created_at;
	}



	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}



	public Date getUpdated_at() {
		return updated_at;
	}



	public void setUpdated_at(Date updated_at) {
		this.updated_at = updated_at;
	}



	public Wallet getWallet() {
		return wallet;
	}



	public void setWallet(Wallet wallet) {
		this.wallet = wallet;
	}
	
public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}


	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(User o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}