package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.Comment;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CommentService extends Serializable {

	public void createComment(Comment newComment);
	
	public void deleteComment(Long id);
	
	public void getCommentById(Long id);

}