package br.ufes.dwws.ufespay.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.transaction.Transactional;

import br.ufes.dwws.ufespay.core.domain.Comment;
import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.dwws.ufespay.core.domain.User;
import br.ufes.dwws.ufespay.core.persistence.CommentDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CommentServiceBean implements CommentService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CommentDAO commentDAO;

	@EJB
	private TransactionService transactionService;

	@EJB
	private UserService userService;

	public void createComment(Comment newComment) {
		this.commentDAO.save(newComment);
	}

	@Transactional
	public Comment createComment(Transaction transac, User author, String message) {
		Comment newComment = new Comment();
		Transaction transComm = transactionService.getTransactionById(transac.getId());
		newComment.setText(message);
		newComment.setAuthor(this.userService.getUserById(author.getId()));
		newComment.setTransaction(transComm);
		transComm.getComments().add(newComment);

		this.commentDAO.save(newComment);
		transactionService.updateTranscation(transComm);

		return newComment;
	}

	public void getCommentById(Long id) {
		this.commentDAO.retrieveById(id);
	}

	@Override
	public void deleteComment(Long id) {
		this.commentDAO.delete(id);
	}

}