package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.Comment;
import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.dwws.ufespay.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CommentService extends Serializable {

	public void createComment(Comment newComment);
	
	public boolean deleteComment(Long idTransac, Long idComment, Long idUser) ;
	
	public void getCommentById(Long id);
	
	public Comment createComment(Transaction transac, User author, String message);
}