package br.ufes.dwws.ufespay.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.dwws.ufespay.core.persistence.TransactionDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class TransactionServiceBean implements TransactionService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private TransactionDAO transactionDAO;

	@Override
	public void createTranscation(Transaction transac) {
		transactionDAO.save(transac);
	}

	@Override
	public Transaction updateTranscation(Transaction transac) {
		return transactionDAO.update(transac);
	}

}