package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.Comment;
import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.dwws.ufespay.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface TransactionService extends Serializable {

	public Transaction createTranscation(User emitter, User receiver, BigDecimal value, String message); 
	
	public void createTranscation(Transaction transac); 

	public Transaction updateTranscation(Transaction transac); 
	
	public List<Transaction> readAllTranscations();

	public List<Comment> retrieveAllComments(Long transacId);
	
	public Transaction getTransactionById(Long transacId);
	
	public Transaction likeTransaction(User user, Transaction transac);
	
	public Transaction disLikeTransaction(User user, Transaction transac);
	
	public List<Transaction> retrieveAllTransactions(String userEmail, boolean asEmitter);
}