package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.Transaction;
import br.ufes.dwws.ufespay.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface TransactionService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void createTranscation(Transaction transac); 
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Transaction updateTranscation(Transaction transac); 

}