package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface UserService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void createUser();
	
	public User getByEmail(String email);
	
	public void updateUser(User user);

}