package br.ufes.dwws.ufespay.core.application;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.ejb.Local;

import br.ufes.dwws.ufespay.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface UserService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public User createUser(String name, String email, String password, BigDecimal initialBalance);
	
	public User getByEmail(String email);
	
	public void updateUser(User user);

}