package br.ufes.dwws.ufespay.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.dwws.ufespay.core.application.CommentService;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CommentController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CommentService commentService;

	/** TODO: generated by FrameWeb. Should be documented. */
	public void createComment() {
		// FIXME: auto-generated method stub
		return;
	}

}