package br.ufes.dwws.ufespay.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.dwws.ufespay.core.application.TransactionService;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class TransactionController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private TransactionService transactionService;

	/** TODO: generated by FrameWeb. Should be documented. */
	public void createTransaction() {
		// FIXME: auto-generated method stub
		return;
	}

}